name: pact_dart
description: Dart DSL for Pact, the de-facto API contract testing tool.
version: 0.8.0
homepage: https://github.com/pact-foundation/pact-dart
repository: https://github.com/pact-foundation/pact-dart

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  ffi: ^2.0.1
  path: ^1.8.0
  http: ^0.13.3
  logging: ^1.0.1

dev_dependencies:
  test: ^1.17.10
  ffigen: ^7.2.11

executables:
  install:

ffigen:
  output: 'lib/gen/library.dart'
  headers:
    entry-points:
      - 'pact.h'
