name: pact_dart
description: Dart DSL for Pact, the de-facto API contract testing tool.
version: 0.8.0
homepage: https://github.com/pact-foundation/pact-dart
repository: https://github.com/pact-foundation/pact-dart

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  ffi: ^2.1.3
  path: ^1.9.0
  http: ^1.2.2
  logging: ^1.3.0

dev_dependencies:
  test: ^1.25.8
  flutter_lints: ^4.0.0

executables:
  install:
