name: pact_dart
description: A Dart DSL for creating pact contracts
version: 0.3.0
homepage: https://github.com/matthewshirley/pact_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
  logger: ^1.0.0
  path: ^1.8.0
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.10

executables:
  install:
