name: pact_dart
description: Dart DSL for Pact, the de-facto API contract testing tool.
version: 0.8.0
homepage: https://github.com/pact-foundation/pact-dart
repository: https://github.com/pact-foundation/pact-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.0.1
  path: ^1.8.0
  logging: ^1.0.1
  http: any
  args: any

dev_dependencies:
  ffigen: ">=9.0.1 <22.0.0"
  test: ^1.29.0

executables:
  install:

ffigen:
  output: "lib/gen/library.dart"
  silence-enum-warning: true
  headers:
    entry-points:
      - "pact.h"
